spring:
  neo4j:
    authentication:
      username: neo4j
      password: bvg
    uri: neo4j://localhost:7687

data:
  directory: data
  file:
    name: lines-and-durations.csv
    header: from,to,line,duration
  rebuildAtStart: false