spring:
  neo4j:
    authentication:
      username: neo4j
      password: bvg

data:
  directory: data
  file:
    name: lines-and-durations.dev.csv
    header: from,to,line,duration
  rebuildAtStart: true